added google ID for RTB
ilri/DSpace pull request #307
Opened 2017-03-09 09:28 UTC by swebshet

Adding google Id and new community

2017-03-12 11:37 UTC, alanorth requested changes
The theme also needs to be added to `dspace/config/xmlui.xconf` for handle `10568/80100`.

2017-03-12 11:37 UTC, alanorth commented on dspace/modules/xmlui-mirage2/src/main/webapp/themes/RTB/sitemap.xmap
> +                <theme-path>HumidTropics</theme-path>
Theme path needs to be `RTB`.

2017-03-12 11:37 UTC, alanorth commented on dspace/modules/xmlui-mirage2/src/main/webapp/themes/RTB/sitemap.xmap
> +                <theme-name>HumidTropics</theme-name>
Theme name needs to be `RTB`.

2017-03-12 11:38 UTC, alanorth commented
In the future, a better commit message would be: Add XMLUI theme for Roots, Tubers, and Bananas (RTB) community.

2017-03-17 06:24 UTC, closed without merging

2017-03-21 10:53 UTC, swebshet commented
Sure, I consider it

On Sun, Mar 12, 2017 at 2:38 PM, Alan Orth <notifications@github.com> wrote:

> In the future, a better commit message would be: Add XMLUI theme for
> Roots, Tubers, and Bananas (RTB) community.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ilri/DSpace/pull/307#issuecomment-285938856>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AG_IxOQbyiEppCK1Tq3zgQV5huDzg9D_ks5rk9lQgaJpZM4MX1fm>
> .
>